spring:
  application:
    name: Astrotalk
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/astrotalk
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.assignment.Astrotalk.controller